language: cpp

matrix:
  include:
  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-8
        - g++-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - BADGE=linux

  - os: osx
    osx_image: xcode10.1
    env:
    - BADGE=osx

  # Hack to get some OS-specific badges
  exclude:
  - os: linux
    env: BADGE=osx

  - os: osx
    env: BADGE=linux

before_install:
- sh ${TRAVIS_BUILD_DIR}/.travis/before_install.sh

install:
- sh ${TRAVIS_BUILD_DIR}/.travis/install.sh

script:
- sh ${TRAVIS_BUILD_DIR}/.travis/script.sh

after_success:
- sh ${TRAVIS_BUILD_DIR}/.travis/after_success.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: cc6IkdalZRb+lOWzPkubCUvTcP9lBwiNBBPkXWVmeX7YXkdQlsoVQ11bZThd1Go+5Lt+jGFtEqEjJ0L7GxpdatEeBMEK5HXl0QtHAybl9J4Ax7hKba8FSX5RqPFOuKixCob6eCqJRchT26qRsQE/WYMY8DmproEFGMBHk0K4HXDWEq0HP8dbWVx3KudvellCYszUrVQYb2s49sDiF8OwSog5TiqdBqO5PRcqyt2ySmHgqwBYq7XV0pb+DxcKJcc7/gCBpBN7nyEhl8gmKELypLF81l8xUDBUjRy1jjf0r33ISHpX1MWeWIN9YzSNL0aLPQvwynAQ7OeckFAIMABah2UuYcxdd4ioXduPTbprVYpSwIyyxkeafK2jxgxwoKWi9GJZ3yAUHNS/V7Gh5DsFb7C6QDqr5gOxOMtjHwjmHnxmD44SsugjSosVzirvQR+JbrSsPsmZThQjCvwG+7hO3JatX4BXA7bp9WtgsoMrCH61gCp2GogQVLvYpgRpVErKK8PMTkt71OouewTDqD5iwc3N/2pNWP3cXxpPegerjl4R2sY0sZ57WRfW8ts7akPyqJZa2uKpzpM0eXy35fZl6WoJSlIv3akCnzdtLtaWAptzfXhgRSlF/33+gZ3jRcSP7ca2YpUviuZ+KYk+uGfMh092CMRMjPv1Et5h7zYGD+o=
  file: "$DEPLOYFILE"
  on:
    repo: sfztools/sfizz
    tags: true
